dtbo-y += gts10fewifi_eur_open_w00_r05.dtbo
dtbo-y += gts10fewifi_eur_open_w00_r04.dtbo
dtbo-y += gts10fewifi_eur_open_w00_r03.dtbo
dtbo-y += gts10fewifi_eur_open_w00_r01.dtbo
dtbo-y += gts10fewifi_eur_open_w00_r00.dtbo
# SPDX-License-Identifier: GPL-2.0

always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo

