obj-$(CONFIG_TFT_COMMON_TEST)		+= tft_common_test.o

obj-$(CONFIG_USDM_PANEL_HX83102J_GTS10FE_BOE_TEST)		+= hx83102j_gts10fe_boe_test.o

obj-$(CONFIG_USDM_PANEL_NT36523N_GTS10FE_CSOT_TEST)		+= nt36523n_gts10fe_csot_test.o
